import { Image } from "react-native";
import React from "react";

export const Level1 = [
  [
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'yellow', state: 3, angle: [-30, -25], visible: true, top: -290},
    {color: 'yellow', state: 3, angle: [-30, -25], visible: true, top: -290},
    {color: 'blue', state: 10, angle: [-20, 5], visible: true, top: -350},
    {color: 'blue', state: 10, angle: [-20, 5], visible: true, top: -350},
    {color: 'blue', state: 10, angle: [-20, 5], visible: true, top: -350},
    {color: 'blue', state: 10, angle: [-20, 5], visible: true, top: -350},
    {color: 'blue', state: 10, angle: [-20, 5], visible: true, top: -350},
    {color: 'blue', state: 10, angle: [-20, 5], visible: true, top: -350},
    {color: 'yellow', state: 7, angle: [10, 25], visible: true, top: -260},
    {color: 'yellow', state: 7, angle: [10, 25], visible: true, top: -260},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
  ],
  [
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'yellow', state: 3, angle: [-30, -25], visible: true, top: -290},
    {color: 'yellow', state: 3, angle: [-40, -26], visible: true, top: -290},
    {color: 'red', state: 4, angle: [-20, -15], visible: true, top: -260},
    {color: 'blue', state: 10, angle: [-20, 5], visible: true, top: -350},
    {color: 'blue', state: 10, angle: [-20, 5], visible: true, top: -350},
    {color: 'red', state: 6, angle: [-4, 9], visible: true, top: -260},
    {color: 'yellow', state: 7, angle: [10, 25], visible: true, top: -260},
    {color: 'yellow', state: 7, angle: [10, 25], visible: true, top: -260},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
  ],
  [
    {color: 'green', state: 1, angle: [-50, -40], visible: true, top: -330},
    {color: 'green', state: 1, angle: [-50, -40], visible: true, top: -330},
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'yellow', state: 3, angle: [-30, -25], visible: true, top: -290},
    {color: 'red', state: 4, angle: [-20, -15], visible: true, top: -260},
    {color: 'red', state: 4, angle: [-20, -15], visible: true, top: -260},
    {color: 'green', state: 5, angle: [-10, 0], visible: true, top: -220},
    {color: 'green', state: 5, angle: [-10, 0], visible: true, top: -220},
    {color: 'red', state: 6, angle: [-4, 9], visible: true, top: -260},
    {color: 'red', state: 6, angle: [-4, 9], visible: true, top: -260},
    {color: 'yellow', state: 7, angle: [10, 25], visible: true, top: -260},
    {color: 'blue', state: 8, angle: [26, 30], visible: true, top: -300},
    {color: 'blue', state: 8, angle: [26, 30], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
  ],
  [
    {color: 'green', state: 1, angle: [-50, -40], visible: true, top: -330},
    {color: 'green', state: 1, angle: [-50, -40], visible: true, top: -330},
    {color: 'green', state: 1, angle: [-50, -40], visible: true, top: -330},
    {color: 'green', state: 1, angle: [-50, -40], visible: true, top: -330},
    {color: 'purple', state: 2, angle: [-39, -35], visible: true, top: -300},
    {color: 'yellow', state: 3, angle: [-30, -25], visible: true, top: -290},
    {color: 'yellow', state: 3, angle: [-30, -25], visible: true, top: -290},
    {color: 'red', state: 4, angle: [-20, -15], visible: true, top: -260},
    {color: 'green', state: 5, angle: [-10, 0], visible: true, top: -220},
    {color: 'green', state: 5, angle: [-10, 0], visible: true, top: -220},
    {color: 'red', state: 6, angle: [0, 5], visible: true, top: -260 },
    {color: 'yellow', state: 7, angle: [10, 25], visible: true, top: -260},
    {color: 'yellow', state: 7, angle: [10, 25], visible: true, top: -260},
    {color: 'blue', state: 8, angle: [26, 30], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
    {color: 'purple', state: 9, angle: [30, 45], visible: true, top: -300},
  ],
];

export const capsuleToShooting = [
  { name: "red", number: 1 },
  { name: "yellow", number: 2 },
  { name: "blue", number: 3 },
  { name: "purple", number: 4 },
  { name: "green", number: 5 },
  { name: "red", number: 1 },
  { name: "yellow", number: 2 },
  { name: "blue", number: 3 },
  { name: "green", number: 5 },
  { name: "purple", number: 4 },
];
